export type CryptoLitePath={
    path:string,methods:
    {
        get?:{
            middlewares?:Array<Function>
        },
        post?:{
            middlewares?:Array<Function>
        },
        delete?:{
            middlewares?:Array<Function>
        },
        put?:{
            middlewares?:Array<Function>
        },
        patch?:{
            middlewares?:Array<Function>
        }
    },
    middlewares:Array<Function>
}